
[data]
  address = "TBD"
  database = "postgresql"
  n_workers = 30
  working_dir = "."

[linking]
  max_distance = 10.0
  max_neighbors = 5
  n_workers = 1

[segmentation]
  anisotropy_penalization = 0.0
  max_area = 10000
  min_area = 500
  min_frontier = 0.05
  n_workers = 1
  threshold = 0.5
  ws_hierarchy = "area"

[tracking]
  appear_weight = -0.002
  bias = 0
  disappear_weight = -0.001
  division_weight = -0.001
  link_function = "power"
  method = -1
  n_threads = 0
  overlap_size = 5
  power = 4
  solution_gap = 0.001
  time_limit = 120000
  window_size = 50
